export const CHAT_CONTEXT_RECENT_MESSAGE_WINDOW = 10;
export const CHAT_CONTEXT_MIN_MESSAGES_FOR_SUMMARY = 14;
export const CHAT_CONTEXT_SUMMARY_REFRESH_BATCH = 4;
export const CHAT_CONTEXT_SUMMARY_MAX_TOKENS = 320;
export const CHAT_CONTEXT_QUERY_REWRITE_MAX_TOKENS = 140;
