import { DocumentResponseDto } from './dto/document-response.dto';
import { DocumentEntity } from './entities/document.entity';

export function toDocumentResponse(entity: DocumentEntity): DocumentResponseDto {
  return {
    id: entity.id,
    shipId: entity.shipId,
    uploadedByUserId: entity.uploadedByUserId,
    originalFileName: entity.originalFileName,
    storageKey: entity.storageKey,
    mimeType: entity.mimeType,
    fileSizeBytes: entity.fileSizeBytes,
    checksumSha256: entity.checksumSha256,
    pageCount: entity.pageCount,
    ragflowDocumentId: entity.ragflowDocumentId,
    ragflowDatasetId: entity.ragflowDatasetId,
    docClass: entity.docClass,
    language: entity.language,
    equipmentOrSystem: entity.equipmentOrSystem,
    manufacturer: entity.manufacturer,
    model: entity.model,
    revision: entity.revision,
    timeScope: entity.timeScope,
    sourcePriority: entity.sourcePriority,
    contentFocus: entity.contentFocus,
    parseProfile: entity.parseProfile,
    chunkMethod: entity.chunkMethod,
    pdfParser: entity.pdfParser,
    autoKeywords: entity.autoKeywords,
    autoQuestions: entity.autoQuestions,
    chunkSize: entity.chunkSize,
    delimiter: entity.delimiter,
    overlapPercent: entity.overlapPercent,
    pageIndexEnabled: entity.pageIndexEnabled,
    childChunksEnabled: entity.childChunksEnabled,
    imageTableContextWindow: entity.imageTableContextWindow,
    parseStatus: entity.parseStatus,
    parseError: entity.parseError,
    parseProgressPercent: entity.parseProgressPercent,
    chunkCount: entity.chunkCount,
    parsedAt: entity.parsedAt?.toISOString() ?? null,
    lastSyncedAt: entity.lastSyncedAt?.toISOString() ?? null,
    metadataJson: entity.metadataJson,
    parserConfigJson: entity.parserConfigJson,
    createdAt: entity.createdAt.toISOString(),
    updatedAt: entity.updatedAt.toISOString(),
  };
}
