import { DocumentChunkMethod } from '../enums/document-chunk-method.enum';
import { DocumentDocClass } from '../enums/document-doc-class.enum';
import { DocumentParseProfile } from '../enums/document-parse-profile.enum';
import { DocumentParseStatus } from '../enums/document-parse-status.enum';
import { DocumentTimeScope } from '../enums/document-time-scope.enum';

export class DocumentResponseDto {
  id!: string;
  shipId!: string;
  uploadedByUserId!: string | null;
  originalFileName!: string;
  storageKey!: string | null;
  mimeType!: string;
  fileSizeBytes!: number;
  checksumSha256!: string;
  pageCount!: number | null;
  ragflowDocumentId!: string | null;
  ragflowDatasetId!: string | null;
  docClass!: DocumentDocClass;
  language!: string | null;
  equipmentOrSystem!: string | null;
  manufacturer!: string | null;
  model!: string | null;
  revision!: string | null;
  timeScope!: DocumentTimeScope;
  sourcePriority!: number;
  contentFocus!: string | null;
  parseProfile!: DocumentParseProfile;
  chunkMethod!: DocumentChunkMethod;
  pdfParser!: string;
  autoKeywords!: number;
  autoQuestions!: number;
  chunkSize!: number | null;
  delimiter!: string | null;
  overlapPercent!: number | null;
  pageIndexEnabled!: boolean;
  childChunksEnabled!: boolean;
  imageTableContextWindow!: number | null;
  parseStatus!: DocumentParseStatus;
  parseError!: string | null;
  parseProgressPercent!: number | null;
  chunkCount!: number | null;
  parsedAt!: string | null;
  lastSyncedAt!: string | null;
  metadataJson!: Record<string, unknown> | null;
  parserConfigJson!: Record<string, unknown> | null;
  createdAt!: string;
  updatedAt!: string;
}
