import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * D1 of the doc-control schema (Trident_DocControl_Field_Schema_v9): tag the
 * compliance catalogue with the 11-archetype model.
 *
 * Adds archetype / link_cardinality / reg_basis / basis_note / drives_pms to
 * both compliance_doc_master (vessel-agnostic, 362 rows) and
 * compliance_doc_types (per-ship rulebook), tags every master row from the
 * agreed schema, then copies the tags onto already-instantiated per-ship
 * types (matched by sfi_code). instantiateForShip carries them forward.
 */
export class TagComplianceArchetypes20260618000700
  implements MigrationInterface
{
  name = 'TagComplianceArchetypes20260618000700';

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const table of ['compliance_doc_master', 'compliance_doc_types']) {
      await queryRunner.query(
        `ALTER TABLE "${table}"
           ADD COLUMN IF NOT EXISTS "archetype" varchar(16),
           ADD COLUMN IF NOT EXISTS "link_cardinality" varchar(16),
           ADD COLUMN IF NOT EXISTS "reg_basis" varchar(200),
           ADD COLUMN IF NOT EXISTS "basis_note" text,
           ADD COLUMN IF NOT EXISTS "drives_pms" varchar(40)`,
      );
    }

    // Tag every master row from the schema (doc_code = sfi_code).
    await queryRunner.query(`
      UPDATE "compliance_doc_master" AS m SET
        "archetype"        = v.archetype,
        "link_cardinality" = v.link_cardinality,
        "reg_basis"        = v.reg_basis,
        "basis_note"       = v.basis_note,
        "drives_pms"       = v.drives_pms
      FROM (VALUES
      ('1.1.1','STAT_CERT','vessel','Flag State registration (national law)','Establishes nationality, title & right to fly the flag','survey'),
      ('1.1.2','STAT_CERT','vessel','Flag YET scheme (e.g. REG / Cayman)','Yacht-specific operational / commercial compliance','survey'),
      ('1.1.3','STAT_CERT','vessel','International Convention on Tonnage Measurement 1969','Official tonnage (manning, fees, rule thresholds)','survey'),
      ('1.1.4','STAT_CERT','vessel','Panama Canal Authority tonnage rules','Canal-transit tonnage for toll assessment','survey'),
      ('1.1.5','STAT_CERT','vessel','Suez Canal Authority tonnage rules','Canal-transit tonnage for toll assessment','survey'),
      ('1.1.6','STAT_CERT','vessel','Flag State registration (national law)','Establishes nationality, title & right to fly the flag','survey'),
      ('1.1.7','STAT_CERT','vessel','Flag State / class (newbuild)','Statutory compliance evidence','survey'),
      ('1.1.8','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.1.9','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.1.10','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.1','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.2','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.3','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.4','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.5','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.6','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.2.7','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.2.8','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.2.9','EQUIP_TYPE','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','no'),
      ('1.2.10','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.11','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.12','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.13','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.2.14','EQUIP_TYPE','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','no'),
      ('1.3.1','STAT_CERT','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','survey'),
      ('1.3.2','STAT_CERT','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','survey'),
      ('1.3.3','STAT_CERT','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','survey'),
      ('1.3.4','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.3.5','STAT_CERT','vessel','SOLAS ch II-1','Construction, stability & machinery safety','survey'),
      ('1.3.6','STAT_CERT','vessel','SOLAS ch II-2 / III','Fire safety — detection / suppression readiness','survey'),
      ('1.3.7','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.3.8','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.3.9','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.3.10','STAT_CERT','vessel','SOLAS I/7','Statutory compliance evidence','survey'),
      ('1.4.1','STAT_CERT','vessel','SOLAS ch IV; ITU Radio Regulations','Radio / GMDSS communications capability','survey'),
      ('1.4.2','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.4.3','STAT_CERT','vessel','SOLAS ch IV; ITU Radio Regulations','Radio / GMDSS communications capability','survey'),
      ('1.4.4','STAT_CERT','vessel','ITU Radio Regulations; SOLAS ch IV','Radio / GMDSS communications capability','survey'),
      ('1.4.5','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.4.6','REPORT','vessel','SOLAS ch IV; ITU Radio Regulations','Radio / GMDSS communications capability','NC close-out'),
      ('1.4.7','REPORT','vessel','SOLAS ch IV; ITU Radio Regulations','Radio / GMDSS communications capability','NC close-out'),
      ('1.4.8','AGREEMENT','vessel',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.4.9','EQUIP_SVC','sub_group','SOLAS V/19-1','Safe-navigation equipment & passage planning','YES'),
      ('1.4.10','STAT_CERT','sub_group','SOLAS IV/7; LSA/radio servicing (res A.1040)','Life-saving appliance readiness','survey'),
      ('1.4.11','EQUIP_SVC','per_unit','SOLAS IV/7; LSA/radio servicing (res A.1040)','Life-saving appliance readiness','YES'),
      ('1.4.12','EQUIP_SVC','per_unit','SOLAS IV/7; LSA/radio servicing (res A.1040)','Life-saving appliance readiness','YES'),
      ('1.4.13','EQUIP_SVC','per_unit','SOLAS IV/7; LSA/radio servicing (res A.1040)','Life-saving appliance readiness','YES'),
      ('1.4.14','EQUIP_SVC','per_unit','SOLAS IV/7; LSA/radio servicing (res A.1040)','Life-saving appliance readiness','YES'),
      ('1.4.15','EQUIP_SVC','sub_group','SOLAS V/19.2.4','Safe-navigation equipment & passage planning','YES'),
      ('1.4.16','EQUIP_SVC','sub_group','SOLAS III/6, ch IV','Life-saving appliance readiness','YES'),
      ('1.4.17','AGREEMENT','per_unit','ITU Radio Regulations; SOLAS ch IV','Radio / GMDSS communications capability','renewal'),
      ('1.4.18','AGREEMENT','per_unit','ITU Radio Regulations; SOLAS ch IV','Radio / GMDSS communications capability','renewal'),
      ('1.4.19','AGREEMENT','per_unit',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.4.20','AGREEMENT','per_unit',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.4.21','AGREEMENT','per_unit',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.4.22','AGREEMENT','per_unit',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.4.23','AGREEMENT','sub_group',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.4.24','STAT_CERT','per_unit',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.4.25','STAT_CERT','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.5.1','STAT_CERT','vessel','International Convention on Load Lines 1966 / 1988 Protocol','Freeboard, watertight integrity & seaworthiness','survey'),
      ('1.5.2','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.5.3','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.5.4','PLAN','vessel','SOLAS II-1/5; IS Code 2008 (res MSC.267(85))','Construction, stability & machinery safety','no'),
      ('1.5.5','PLAN','vessel','SOLAS II-1/5-1','Construction, stability & machinery safety','no'),
      ('1.5.6','PLAN','vessel','SOLAS II-1; class rules','Construction, stability & machinery safety','no'),
      ('1.6.1','STAT_CERT','vessel','MARPOL Annex I','Oil-pollution prevention compliance','survey'),
      ('1.6.2','STAT_CERT','vessel','MARPOL Annex I','Oil-pollution prevention compliance','survey'),
      ('1.6.3','STAT_CERT','vessel','MARPOL Annex VI','Air-emission & energy-efficiency compliance','survey'),
      ('1.6.4','STAT_CERT','vessel','MARPOL Annex VI','Air-emission & energy-efficiency compliance','survey'),
      ('1.6.5','STAT_CERT','vessel','MARPOL Annex IV','Sewage discharge compliance','survey'),
      ('1.6.6','STAT_CERT','vessel','MARPOL Annex IV','Sewage discharge compliance','survey'),
      ('1.6.7','STAT_CERT','vessel','MARPOL Annex V','Garbage management & discharge compliance','survey'),
      ('1.6.8','STAT_CERT','vessel','AFS Convention 2001','Anti-fouling system compliance','survey'),
      ('1.6.9','STAT_CERT','vessel','AFS Convention 2001','Anti-fouling system compliance','survey'),
      ('1.6.10','STAT_CERT','vessel','BWM Convention 2004','Ballast-water management compliance','survey'),
      ('1.6.11','STAT_CERT','vessel','BWM Convention 2004','Ballast-water management compliance','survey'),
      ('1.6.12','STAT_CERT','vessel','MARPOL Annex I reg 37','Oil-pollution prevention compliance','survey'),
      ('1.6.13','EQUIP_SVC','per_unit','MARPOL Annex I reg 14','Oil-pollution prevention compliance','YES'),
      ('1.6.14','EQUIP_TYPE','per_unit','MARPOL Annex VI reg 13 + NOx Technical Code 2008','Air-emission & energy-efficiency compliance','no'),
      ('1.6.15','PLAN','per_unit','MARPOL Annex VI reg 13 + NOx Technical Code 2008','Air-emission & energy-efficiency compliance','no'),
      ('1.6.16','EQUIP_TYPE','per_unit','MARPOL Annex VI reg 13 + NOx Technical Code 2008','Air-emission & energy-efficiency compliance','no'),
      ('1.6.17','PLAN','per_unit','MARPOL Annex VI reg 13 + NOx Technical Code 2008','Air-emission & energy-efficiency compliance','no'),
      ('1.6.18','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.7.1','STAT_CERT','vessel','MARPOL Annex VI ch 4 (energy efficiency)','Air-emission & energy-efficiency compliance','survey'),
      ('1.7.2','STAT_CERT','vessel','MARPOL Annex VI ch 4 (energy efficiency)','Air-emission & energy-efficiency compliance','survey'),
      ('1.7.3','PLAN','vessel','MARPOL Annex VI reg 25','Air-emission & energy-efficiency compliance','no'),
      ('1.7.4','PLAN','vessel','MARPOL Annex VI reg 24-25','Air-emission & energy-efficiency compliance','no'),
      ('1.7.5','STAT_CERT','vessel','MARPOL Annex VI reg 28','Air-emission & energy-efficiency compliance','survey'),
      ('1.7.6','PLAN','vessel','MARPOL Annex VI reg 26-28','Air-emission & energy-efficiency compliance','no'),
      ('1.7.7','PLAN','vessel','MARPOL Annex VI reg 26-28','Air-emission & energy-efficiency compliance','no'),
      ('1.7.8','PLAN','vessel','MARPOL Annex VI reg 26-28','Air-emission & energy-efficiency compliance','no'),
      ('1.7.9','REPORT','vessel','MARPOL Annex VI reg 27 (fuel oil data collection)','Air-emission & energy-efficiency compliance','NC close-out'),
      ('1.7.10','STAT_CERT','vessel','MARPOL Annex VI reg 27 (fuel oil data collection)','Air-emission & energy-efficiency compliance','survey'),
      ('1.7.11','PLAN','vessel','EU Reg 2015/757','Statutory compliance evidence','no'),
      ('1.7.12','REPORT','vessel','EU Reg 2015/757','Statutory compliance evidence','NC close-out'),
      ('1.7.13','RECORD_BOOK','vessel','EU ETS Directive 2003/87/EC (maritime extension)','EU/UK carbon reporting & market compliance','retention'),
      ('1.7.14','PLAN','vessel','UK MRV Regulations','EU/UK carbon reporting & market compliance','no'),
      ('1.7.15','STAT_CERT','vessel','FuelEU Maritime Reg (EU) 2023/1805','EU/UK carbon reporting & market compliance','survey'),
      ('1.8.1','STAT_CERT','vessel','ISM Code (SOLAS ch IX)','Safety-management-system compliance','survey'),
      ('1.8.2','STAT_CERT','vessel','ISM Code (SOLAS ch IX)','Safety-management-system compliance','survey'),
      ('1.8.3','STAT_CERT','vessel','ISM Code (SOLAS ch IX)','Safety-management-system compliance','survey'),
      ('1.8.4','STAT_CERT','vessel','ISPS Code (SOLAS XI-2)','Ship-security compliance','survey'),
      ('1.8.5','STAT_CERT','vessel','ISPS Code (SOLAS XI-2)','Ship-security compliance','survey'),
      ('1.8.6','RECORD_BOOK','vessel','SOLAS XI-1/5','Vessel history / identification (CSR)','retention'),
      ('1.8.7','STAT_CERT','vessel','MLC 2006','Seafarer living & working conditions','survey'),
      ('1.8.8','STAT_CERT','vessel','MLC 2006','Seafarer living & working conditions','survey'),
      ('1.8.9','STAT_CERT','vessel','MLC 2006','Seafarer living & working conditions','survey'),
      ('1.8.10','STAT_CERT','vessel','MLC 2006','Seafarer living & working conditions','survey'),
      ('1.8.11','STAT_CERT','vessel','SOLAS V/14; IMO res A.1047(27)','Safe-navigation equipment & passage planning','survey'),
      ('1.8.12','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.8.13','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.8.14','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.8.15','REPORT','vessel','ISM Code (SOLAS ch IX)','Safety-management-system compliance','NC close-out'),
      ('1.8.16','REPORT','vessel','ISM Code (SOLAS ch IX)','Safety-management-system compliance','NC close-out'),
      ('1.8.17','REPORT','vessel','ISPS Code (SOLAS XI-2)','Ship-security compliance','NC close-out'),
      ('1.8.18','REPORT','vessel','MLC 2006','Seafarer living & working conditions','NC close-out'),
      ('1.8.19','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.8.20','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.9.1','STAT_CERT','vessel','International Health Regulations 2005','Public-health / sanitation compliance','survey'),
      ('1.9.2','EQUIP_SVC','sub_group','SOLAS V/19.2.1 (deviation)','Safe-navigation equipment & passage planning','YES'),
      ('1.9.3','EQUIP_SVC','sub_group','SOLAS V/19.2.1 (deviation)','Safe-navigation equipment & passage planning','YES'),
      ('1.9.4','AGREEMENT','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','renewal'),
      ('1.9.5','AGREEMENT','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','renewal'),
      ('1.9.6','AGREEMENT','vessel',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.9.7','AGREEMENT','vessel',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.9.8','AGREEMENT','vessel','STCW reg I/9; MLC A1.2','Seafarer living & working conditions','renewal'),
      ('1.9.9','AGREEMENT','vessel',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.9.10','AGREEMENT','vessel',NULL,'Commercial service / subscription contract — governed by supplier terms','renewal'),
      ('1.9.11','RECORD_BOOK','vessel','SOLAS III/20; LSA Code; res MSC.402(96)','Life-saving appliance readiness','retention'),
      ('1.9.12','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.9.13','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.9.14','STAT_CERT','vessel','International Health Regulations 2005','Public-health / sanitation compliance','survey'),
      ('1.10.1','LEGAL','vessel',NULL,'Evidence of title transfer — legal instrument, required by registry but not a maritime cert','no'),
      ('1.10.2','LEGAL','vessel',NULL,'Tax / customs status (EU VAT) — fiscal, not maritime statute','no'),
      ('1.10.3','LEGAL','vessel',NULL,'Tax / customs status (EU VAT) — fiscal, not maritime statute','no'),
      ('1.10.4','LEGAL','vessel',NULL,'Delegated signing authority — corporate/legal','no'),
      ('1.10.5','LEGAL','vessel',NULL,'Owning-company existence — company law','no'),
      ('1.10.6','LEGAL','vessel',NULL,'AML / KYC due diligence — banking & registry requirement','no'),
      ('1.10.7','LEGAL','vessel',NULL,'Ownership-structure documentation — corporate/legal','no'),
      ('1.10.8','LEGAL','vessel',NULL,'Commercial contract (owner ↔ manager) — governed by its own terms','no'),
      ('1.10.9','LEGAL','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','no'),
      ('1.10.10','RECORD_BOOK','vessel','MLC 2006 (Std A2.1)','Seafarer living & working conditions','retention'),
      ('1.11.1','INSURANCE','vessel',NULL,'Commercial insurance cover — carried for protection / charter terms, not convention-mandated','no'),
      ('1.11.2','INSURANCE','vessel',NULL,'Commercial insurance cover — carried for protection / charter terms, not convention-mandated','no'),
      ('1.11.3','INSURANCE','vessel',NULL,'Commercial insurance cover — carried for protection / charter terms, not convention-mandated','no'),
      ('1.11.4','INSURANCE','vessel',NULL,'Commercial insurance cover — carried for protection / charter terms, not convention-mandated','no'),
      ('1.11.5','INSURANCE','vessel',NULL,'Commercial insurance cover — carried for protection / charter terms, not convention-mandated','no'),
      ('1.11.6','INSURANCE','vessel','MLC 2006','Seafarer living & working conditions','no'),
      ('1.11.7','INSURANCE','vessel','MLC 2006','Seafarer living & working conditions','no'),
      ('1.11.8','INSURANCE','vessel','Nairobi Wreck Removal Convention 2007','Mandatory financial-security / civil-liability cover','no'),
      ('1.11.9','INSURANCE','vessel',NULL,'Commercial insurance cover — carried for protection / charter terms, not convention-mandated','no'),
      ('1.11.10','INSURANCE','vessel','CLC 1992 (oil pollution civil liability)','Mandatory financial-security / civil-liability cover','no'),
      ('1.11.11','INSURANCE','vessel','CLC 1992 (oil pollution civil liability)','Mandatory financial-security / civil-liability cover','no'),
      ('1.11.12','INSURANCE','vessel','STCW reg I/9; MLC A1.2','Seafarer living & working conditions','no'),
      ('1.11.13','INSURANCE','vessel',NULL,'Commercial insurance cover — carried for protection / charter terms, not convention-mandated','no'),
      ('1.11.14','INSURANCE','vessel',NULL,'Commercial insurance cover — carried for protection / charter terms, not convention-mandated','no'),
      ('1.11.15','INSURANCE','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','no'),
      ('1.12.1','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.2','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.3','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.4','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.5','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.6','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.7','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.8','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.9','STAT_CERT','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','survey'),
      ('1.12.10','STAT_CERT','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','survey'),
      ('1.12.11','STAT_CERT','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','survey'),
      ('1.12.12','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.13','STAT_CERT','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','survey'),
      ('1.12.14','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.15','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.16','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.17','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.12.18','STAT_CERT','vessel',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.13.1','EQUIP_SVC','per_unit','SOLAS III/20; LSA Code; res MSC.402(96)','Life-saving appliance readiness','YES'),
      ('1.13.2','EQUIP_SVC','per_unit','SOLAS III/20; LSA Code; res MSC.402(96)','Life-saving appliance readiness','YES'),
      ('1.13.3','EQUIP_SVC','sub_group','SOLAS III/20; LSA Code; res MSC.402(96)','Life-saving appliance readiness','YES'),
      ('1.13.4','EQUIP_SVC','sub_group','SOLAS III/20; LSA Code','Life-saving appliance readiness','YES'),
      ('1.13.5','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.6','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.7','EQUIP_SVC','per_unit',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.8','EQUIP_SVC','sub_group','SOLAS III/20; LSA Code','Life-saving appliance readiness','YES'),
      ('1.13.9','STAT_CERT','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.13.10','STAT_CERT','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.13.11','STAT_CERT','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','survey'),
      ('1.13.12','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.13','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.14','EQUIP_SVC','sub_group','SOLAS II-2/7; FSS Code','Fire safety — detection / suppression readiness','YES'),
      ('1.13.15','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.16','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.17','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.18','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.19','EQUIP_SVC','sub_group','SOLAS II-2/10; FSS Code','Fire safety — detection / suppression readiness','YES'),
      ('1.13.20','EQUIP_SVC','sub_group','SOLAS II-2/10; FSS Code','Fire safety — detection / suppression readiness','YES'),
      ('1.13.21','EQUIP_SVC','sub_group','SOLAS II-2/10; FSS Code','Fire safety — detection / suppression readiness','YES'),
      ('1.13.22','EQUIP_SVC','sub_group','SOLAS II-2/10; FSS Code','Fire safety — detection / suppression readiness','YES'),
      ('1.13.23','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.13.24','EQUIP_SVC','sub_group','SOLAS II-2/14; FSS Code','Fire safety — detection / suppression readiness','YES'),
      ('1.13.25','EQUIP_SVC','sub_group','SOLAS II-2/14; FSS Code; MSC.1/Circ.1432','Fire safety — detection / suppression readiness','YES'),
      ('1.13.26','EQUIP_SVC','sub_group','SOLAS II-2/14; FSS Code; MSC.1/Circ.1432','Fire safety — detection / suppression readiness','YES'),
      ('1.13.27','EQUIP_SVC','sub_group','SOLAS II-2/14; FSS Code','Fire safety — detection / suppression readiness','YES'),
      ('1.13.28','EQUIP_SVC','per_unit',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.1','EQUIP_SVC','sub_group','ILO C152 / class lifting-appliance rules','Lifting-gear safety & test certification','YES'),
      ('1.14.2','EQUIP_SVC','sub_group','ILO C152 / class lifting-appliance rules','Lifting-gear safety & test certification','YES'),
      ('1.14.3','EQUIP_TYPE','single_asset','SOLAS III/20; LSA Code; res MSC.402(96)','Life-saving appliance readiness','no'),
      ('1.14.4','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.5','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.6','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.7','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.8','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.9','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.10','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.11','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.12','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.13','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.14','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.15','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.16','EQUIP_SVC','sub_group',NULL,'No standalone statutory basis — governed by contract / flag / class','YES'),
      ('1.14.17','EQUIP_SVC','sub_group','ILO C152 / class lifting-appliance rules','Lifting-gear safety & test certification','YES'),
      ('1.14.18','RECORD_BOOK','vessel','ILO C152 / flag cargo-gear regs (yacht: LOLER + class)','Lifting-gear safety & test certification','retention'),
      ('1.15.1','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.2','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.3','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.4','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.5','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.6','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.7','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.8','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.9','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.10','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.11','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.12','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.13','PERSONNEL','person','STCW 1978 as amended (Manila 2010)','Crew competency / certification','reval'),
      ('1.15.14','PERSONNEL','person',NULL,'No standalone statutory basis — governed by contract / flag / class','reval'),
      ('1.15.15','PERSONNEL','person','STCW reg I/9; MLC A1.2','Seafarer living & working conditions','reval'),
      ('1.15.16','PERSONNEL','person',NULL,'No standalone statutory basis — governed by contract / flag / class','reval'),
      ('1.15.17','PERSONNEL','person',NULL,'No standalone statutory basis — governed by contract / flag / class','reval'),
      ('1.15.18','PERSONNEL','person','MLC 2006 (Std A2.1)','Seafarer living & working conditions','reval'),
      ('1.15.19','PERSONNEL','person',NULL,'No standalone statutory basis — governed by contract / flag / class','reval'),
      ('1.15.20','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.15.21','PERSONNEL','person',NULL,'No standalone statutory basis — governed by contract / flag / class','reval'),
      ('1.16.1','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.2','PLAN','vessel','SOLAS II-2/14; FSS Code','Fire safety — detection / suppression readiness','no'),
      ('1.16.3','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.4','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.5','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.6','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.7','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.8','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.9','PLAN','vessel','MARPOL Annex I reg 37','Oil-pollution prevention compliance','no'),
      ('1.16.10','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.11','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.12','PLAN','vessel','ISPS Code (SOLAS XI-2)','Ship-security compliance','no'),
      ('1.16.13','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.14','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.16.15','PLAN','vessel','MARPOL Annex VI reg 13 + NOx Technical Code 2008','Air-emission & energy-efficiency compliance','no'),
      ('1.16.16','PLAN','vessel','MARPOL Annex V','Garbage management & discharge compliance','no'),
      ('1.16.17','PLAN','vessel','BWM Convention 2004','Ballast-water management compliance','no'),
      ('1.16.18','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.19','PLAN','vessel','SOLAS III/8 & III/37','Life-saving appliance readiness','no'),
      ('1.16.20','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.21','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.16.22','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.17.1','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.2','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.3','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.4','PUBLICATION','vessel','International Convention on Load Lines 1966 / 1988 Protocol','Freeboard, watertight integrity & seaworthiness','corrections'),
      ('1.17.5','PUBLICATION','vessel','STCW 1978 as amended (Manila 2010)','Crew competency / certification','corrections'),
      ('1.17.6','PUBLICATION','vessel','ISM Code (SOLAS ch IX)','Safety-management-system compliance','corrections'),
      ('1.17.7','PUBLICATION','vessel','ISPS Code (SOLAS XI-2)','Ship-security compliance','corrections'),
      ('1.17.8','PUBLICATION','vessel','MLC 2006','Seafarer living & working conditions','corrections'),
      ('1.17.9','PUBLICATION','vessel','International Convention on Tonnage Measurement 1969','Official tonnage (manning, fees, rule thresholds)','corrections'),
      ('1.17.10','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.11','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.12','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.13','PUBLICATION','vessel','SOLAS II-2/14; FSS Code','Fire safety — detection / suppression readiness','corrections'),
      ('1.17.14','PUBLICATION','vessel','SOLAS II-1/5; IS Code 2008 (res MSC.267(85))','Construction, stability & machinery safety','corrections'),
      ('1.17.15','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.16','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.17','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.18','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.19','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.20','PUBLICATION','vessel','SOLAS ch IV; ITU Radio Regulations','Radio / GMDSS communications capability','corrections'),
      ('1.17.21','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.22','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.23','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.24','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.25','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.26','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.27','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.28','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.29','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.30','PUBLICATION','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','corrections'),
      ('1.17.31','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.32','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.33','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.34','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.35','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.36','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.37','PUBLICATION','vessel','SOLAS ch IV; ITU Radio Regulations','Radio / GMDSS communications capability','corrections'),
      ('1.17.38','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.39','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.40','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.41','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.42','PUBLICATION','vessel','SOLAS V/27; V/19.2.1.4','Safe-navigation equipment & passage planning','corrections'),
      ('1.17.43','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.44','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.45','PUBLICATION','vessel','MLC 2006','Seafarer living & working conditions','corrections'),
      ('1.17.46','PUBLICATION','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','corrections'),
      ('1.17.47','PUBLICATION','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','corrections'),
      ('1.17.48','PUBLICATION','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','corrections'),
      ('1.17.49','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.50','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.51','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.52','PUBLICATION','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','corrections'),
      ('1.17.53','PUBLICATION','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','corrections'),
      ('1.17.54','PUBLICATION','vessel','REG Yacht Code (PYC/LY3) / flag','Yacht-specific operational / commercial compliance','corrections'),
      ('1.17.55','PUBLICATION','vessel','STCW reg I/9; MLC A1.2','Seafarer living & working conditions','corrections'),
      ('1.17.56','PUBLICATION','vessel','STCW reg I/9; MLC A1.2','Seafarer living & working conditions','corrections'),
      ('1.17.57','PUBLICATION','vessel','STCW reg I/9; MLC A1.2','Seafarer living & working conditions','corrections'),
      ('1.17.58','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.59','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.60','PUBLICATION','vessel','ISM Code (SOLAS ch IX)','Safety-management-system compliance','corrections'),
      ('1.17.61','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.62','PUBLICATION','vessel','STCW reg I/9; MLC A1.2','Seafarer living & working conditions','corrections'),
      ('1.17.63','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.64','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.65','RECORD_BOOK','vessel','MARPOL Annex I reg 17','Oil-pollution prevention compliance','retention'),
      ('1.17.66','RECORD_BOOK','vessel','MARPOL Annex I reg 17','Oil-pollution prevention compliance','retention'),
      ('1.17.67','RECORD_BOOK','vessel','MARPOL Annex V','Garbage management & discharge compliance','retention'),
      ('1.17.68','RECORD_BOOK','vessel','BWM Convention 2004','Ballast-water management compliance','retention'),
      ('1.17.69','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.70','RECORD_BOOK','vessel','MARPOL Annex VI reg 12','Air-emission & energy-efficiency compliance','retention'),
      ('1.17.71','RECORD_BOOK','vessel','MARPOL Annex VI reg 13 / NOx Technical Code (onboard verification)','Air-emission & energy-efficiency compliance','retention'),
      ('1.17.72','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.73','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.74','RECORD_BOOK','vessel','SOLAS ch IV; ITU Radio Regulations','Radio / GMDSS communications capability','retention'),
      ('1.17.75','PUBLICATION','vessel','SOLAS III/20; LSA Code; res MSC.402(96)','Life-saving appliance readiness','corrections'),
      ('1.17.76','PUBLICATION','vessel','SOLAS II-2/14; FSS Code','Fire safety — detection / suppression readiness','corrections'),
      ('1.17.77','PUBLICATION','vessel','SOLAS II-2/14; FSS Code','Fire safety — detection / suppression readiness','corrections'),
      ('1.17.78','RECORD_BOOK','vessel','SOLAS III/8 & III/37','Life-saving appliance readiness','retention'),
      ('1.17.79','PUBLICATION','vessel','SOLAS II-1/19; res A.952(23)','Construction, stability & machinery safety','corrections'),
      ('1.17.80','PUBLICATION','vessel','STCW 1978 as amended (Manila 2010)','Crew competency / certification','corrections'),
      ('1.17.81','RECORD_BOOK','vessel','ISPS Code (SOLAS XI-2)','Ship-security compliance','retention'),
      ('1.17.82','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.83','REPORT','vessel',NULL,'Survey / audit output — evidences compliance rather than being mandated itself','NC close-out'),
      ('1.17.84','PLAN','vessel',NULL,'Technical / working document — version-controlled; carriage may be implied by class or SOLAS, not a standalone cert','no'),
      ('1.17.85','PLAN','vessel','SOLAS II-1/3-7; MSC/Circ.1135','Construction, stability & machinery safety','no'),
      ('1.17.86','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.87','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.88','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.89','PUBLICATION','vessel',NULL,'Reference publication — currency expected under SOLAS V/27; item itself isn’t certified','corrections'),
      ('1.17.90','RECORD_BOOK','vessel','SOLAS V/27','Safe-navigation equipment & passage planning','retention'),
      ('1.17.91','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.92','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.93','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.94','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.95','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.96','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.97','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention'),
      ('1.17.98','RECORD_BOOK','vessel',NULL,'Operational record — retention obligation flows from the related instrument','retention')
      ) AS v(code, archetype, link_cardinality, reg_basis, basis_note, drives_pms)
      WHERE m."sfi_code" = v.code
    `);

    // Copy the tags onto per-ship rulebook rows already instantiated.
    await queryRunner.query(`
      UPDATE "compliance_doc_types" AS t SET
        "archetype"        = m."archetype",
        "link_cardinality" = m."link_cardinality",
        "reg_basis"        = m."reg_basis",
        "basis_note"       = m."basis_note",
        "drives_pms"       = m."drives_pms"
      FROM "compliance_doc_master" AS m
      WHERE t."sfi_code" = m."sfi_code"
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const table of ['compliance_doc_master', 'compliance_doc_types']) {
      await queryRunner.query(
        `ALTER TABLE "${table}"
           DROP COLUMN IF EXISTS "archetype",
           DROP COLUMN IF EXISTS "link_cardinality",
           DROP COLUMN IF EXISTS "reg_basis",
           DROP COLUMN IF EXISTS "basis_note",
           DROP COLUMN IF EXISTS "drives_pms"`,
      );
    }
  }
}
