// AUTO-GENERATED from Trident_SFI_Master_generic.xlsx (2026-07-10).
// Level 1 = groups, level 2 = sub-groups (X.Y). The register's sfi_sub uses level 2.

export interface SfiTaxonomySeed {
  code: string;
  name: string;
  level: number;
  groupCode: string;
  parentCode: string | null;
  defaultZone: string | null;
  source: string;
  sortOrder: number;
}

export const SFI_TAXONOMY: SfiTaxonomySeed[] = [
  { code: "1", name: "Hull & Structure", level: 1, groupCode: "1", parentCode: null, defaultZone: null, source: "master", sortOrder: 1 },
  { code: "1.1", name: "Hull Structure & Underwater Body", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 2 },
  { code: "1.2", name: "Sacrificial Anodes", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 3 },
  { code: "1.3", name: "Cathodic Protection & Antifouling", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 4 },
  { code: "1.4", name: "Exterior Deck & Superstructure", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 5 },
  { code: "1.5", name: "External Doors & Openings", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 6 },
  { code: "1.6", name: "Hatches & Deck Access", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 7 },
  { code: "1.7", name: "Mast, Rigging & Aerials", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 8 },
  { code: "1.8", name: "Tanks — Hull Integral", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 9 },
  { code: "1.9", name: "Cathodic Protection — Hull Anodes & Monitoring", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 10 },
  { code: "1.10", name: "Hull Penetrations Reference", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 11 },
  { code: "1.11", name: "Overboard Valves & Sea Valves", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 12 },
  { code: "1.15", name: "Glazing", level: 2, groupCode: "1", parentCode: "1", defaultZone: null, source: "master", sortOrder: 13 },
  { code: "2", name: "Propulsion & Power Generation", level: 1, groupCode: "2", parentCode: null, defaultZone: null, source: "master", sortOrder: 14 },
  { code: "2.1", name: "Main Engines", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 15 },
  { code: "2.2", name: "Main Propulsion Motors (E-Drive / PEM)", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 16 },
  { code: "2.3", name: "Diesel Generator Sets", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 17 },
  { code: "2.4", name: "Propulsion Power Converters & DC Bus", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 18 },
  { code: "2.5", name: "Propeller & Shaftline", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 19 },
  { code: "2.6", name: "Steering Gear & Rudders", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 20 },
  { code: "2.7", name: "Bow & Stern Thrusters", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 21 },
  { code: "2.8", name: "Gearboxes & Flexible Couplings", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 22 },
  { code: "2.9", name: "Exhaust Systems & Gas Treatment", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 23 },
  { code: "2.10", name: "Battery Energy Storage System", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 24 },
  { code: "2.11", name: "Urea / AdBlue (DEF) System", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 25 },
  { code: "2.12", name: "Stabilisation Systems", level: 2, groupCode: "2", parentCode: "2", defaultZone: null, source: "master", sortOrder: 26 },
  { code: "3", name: "Machinery Systems", level: 1, groupCode: "3", parentCode: null, defaultZone: null, source: "master", sortOrder: 27 },
  { code: "3.1", name: "Fuel Storage & Transfer", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 28 },
  { code: "3.2", name: "Fuel Treatment & Filtration", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 29 },
  { code: "3.3", name: "Lube Oil System", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 30 },
  { code: "3.4", name: "Sea Water Cooling System", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 31 },
  { code: "3.5", name: "Glycol Cooling System", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 32 },
  { code: "3.6", name: "Heat Exchangers", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 33 },
  { code: "3.7", name: "Compressed Air System", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 34 },
  { code: "3.8", name: "Breathing Air System & Sea Chests", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 35 },
  { code: "3.9", name: "Bilge System", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 36 },
  { code: "3.10", name: "Oily Water Separator", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 37 },
  { code: "3.11", name: "Fire Pumps", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 38 },
  { code: "3.12", name: "Hydraulic Systems (Legacy)", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 39 },
  { code: "3.13", name: "Technical Systems — Urea / AdBlue", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 40 },
  { code: "3.14", name: "Lifts, Elevators & Dumbwaiters", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 41 },
  { code: "3.15", name: "Petrol / Gasoline System", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 42 },
  { code: "3.16", name: "Aviation Fuel System", level: 2, groupCode: "3", parentCode: "3", defaultZone: null, source: "master", sortOrder: 43 },
  { code: "4", name: "Electrical Systems", level: 1, groupCode: "4", parentCode: null, defaultZone: null, source: "master", sortOrder: 44 },
  { code: "4.1", name: "Battery Packs", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 45 },
  { code: "4.2", name: "Battery Chargers", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 46 },
  { code: "4.3", name: "Battery Switchboards", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 47 },
  { code: "4.4", name: "UPS Systems", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 48 },
  { code: "4.5", name: "Shore Power & Cable Systems", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 49 },
  { code: "4.6", name: "Isolation Transformers", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 50 },
  { code: "4.7", name: "Power Distribution & Management", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 51 },
  { code: "4.8", name: "Battery Locker Ventilation & BMS", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 52 },
  { code: "4.9", name: "Underwater Lights", level: 2, groupCode: "4", parentCode: "4", defaultZone: null, source: "master", sortOrder: 53 },
  { code: "5", name: "HVAC & Refrigeration", level: 1, groupCode: "5", parentCode: null, defaultZone: null, source: "master", sortOrder: 54 },
  { code: "5.1", name: "Chiller Units", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 55 },
  { code: "5.2", name: "Chilled Water System", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 56 },
  { code: "5.3", name: "Fan Coil Units", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 57 },
  { code: "5.4", name: "Air Handling Units (AHUs) — Conditioning", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 58 },
  { code: "5.5", name: "Fresh Air Supply Units", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 59 },
  { code: "5.6", name: "Supply Fans", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 60 },
  { code: "5.7", name: "Exhaust Fans", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 61 },
  { code: "5.8", name: "Engine Room Ventilation System", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 62 },
  { code: "5.9", name: "Freezers & Ice Makers", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 63 },
  { code: "5.10", name: "Refrigerators", level: 2, groupCode: "5", parentCode: "5", defaultZone: null, source: "master", sortOrder: 64 },
  { code: "6", name: "Water Systems", level: 1, groupCode: "6", parentCode: null, defaultZone: null, source: "master", sortOrder: 65 },
  { code: "6.1", name: "Watermakers", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 66 },
  { code: "6.2", name: "Hot & Cold Fresh Water Distribution", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 67 },
  { code: "6.3", name: "Hot Water System", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 68 },
  { code: "6.4", name: "Water Treatment & Conditioning", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 69 },
  { code: "6.5", name: "Pool & Spa Systems", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 70 },
  { code: "6.6", name: "Shore Services", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 71 },
  { code: "6.7", name: "Sewage & Waste Water Treatment", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 72 },
  { code: "6.8", name: "Waste Water Pumps / Fresh Water Treatment", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 73 },
  { code: "6.9", name: "Toilets & Vacuum Tanks", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 74 },
  { code: "6.10", name: "Deck Shower Outlets", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 75 },
  { code: "6.11", name: "Ozone Generator", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 76 },
  { code: "6.12", name: "Deck Wash Systems", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 77 },
  { code: "6.13", name: "Deck Drainage & Scuppers", level: 2, groupCode: "6", parentCode: "6", defaultZone: null, source: "master", sortOrder: 78 },
  { code: "7", name: "Fire, Safety & Security", level: 1, groupCode: "7", parentCode: null, defaultZone: null, source: "master", sortOrder: 79 },
  { code: "7.1", name: "Emergency Lighting", level: 2, groupCode: "7", parentCode: "7", defaultZone: null, source: "master", sortOrder: 80 },
  { code: "7.2", name: "Fire Hoses & Life-Saving Rings", level: 2, groupCode: "7", parentCode: "7", defaultZone: null, source: "master", sortOrder: 81 },
  { code: "7.3", name: "Fixed Firefighting Systems", level: 2, groupCode: "7", parentCode: "7", defaultZone: null, source: "master", sortOrder: 82 },
  { code: "7.4", name: "Life-Saving Appliances (LSA)", level: 2, groupCode: "7", parentCode: "7", defaultZone: null, source: "master", sortOrder: 83 },
  { code: "7.5", name: "Fire Detection System", level: 2, groupCode: "7", parentCode: "7", defaultZone: null, source: "master", sortOrder: 84 },
  { code: "7.7", name: "Fire Doors, Dampers & Boundaries", level: 2, groupCode: "7", parentCode: "7", defaultZone: null, source: "master", sortOrder: 85 },
  { code: "7.8", name: "CCTV & Security", level: 2, groupCode: "7", parentCode: "7", defaultZone: null, source: "master", sortOrder: 86 },
  { code: "7.9", name: "Gas Detection System", level: 2, groupCode: "7", parentCode: "7", defaultZone: null, source: "master", sortOrder: 87 },
  { code: "8", name: "Navigation, Bridge & Comms", level: 1, groupCode: "8", parentCode: null, defaultZone: null, source: "master", sortOrder: 88 },
  { code: "8.1", name: "Radar & Navigation Displays", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 89 },
  { code: "8.2", name: "Compass Systems", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 90 },
  { code: "8.3", name: "GPS & GNSS", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 91 },
  { code: "8.4", name: "AIS", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 92 },
  { code: "8.5", name: "GMDSS & Communications", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 93 },
  { code: "8.6", name: "Autopilot & Steering", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 94 },
  { code: "8.7", name: "Navigation Sensors & Transducers", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 95 },
  { code: "8.8", name: "Meteorological Instruments", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 96 },
  { code: "8.9", name: "Navigation Lights & BNWAS", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 97 },
  { code: "8.10", name: "Satellite Internet", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 98 },
  { code: "8.11", name: "Alarm & Monitoring System (AMS)", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 99 },
  { code: "8.12", name: "Wheelhouse Window Systems", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 100 },
  { code: "8.13", name: "Sound Signals", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 101 },
  { code: "8.14", name: "Helideck Lighting & Visual Aids", level: 2, groupCode: "8", parentCode: "8", defaultZone: null, source: "master", sortOrder: 102 },
  { code: "9", name: "AV, IT & Automation", level: 1, groupCode: "9", parentCode: null, defaultZone: null, source: "master", sortOrder: 103 },
  { code: "9.1", name: "Bridge Equipment", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 104 },
  { code: "9.2", name: "Audio Systems", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 105 },
  { code: "9.3", name: "Video & Display Systems", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 106 },
  { code: "9.4", name: "Networking & IT Infrastructure", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 107 },
  { code: "9.5", name: "Lighting Automation & Control", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 108 },
  { code: "9.6", name: "CCTV & Surveillance", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 109 },
  { code: "9.7", name: "Cellular / WiFi / 5G Antennas", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 110 },
  { code: "9.8", name: "Videoworks AV Integration System", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 111 },
  { code: "9.9", name: "Internal Communications", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 112 },
  { code: "9.10", name: "Night Vision & Thermal Imaging", level: 2, groupCode: "9", parentCode: "9", defaultZone: null, source: "master", sortOrder: 113 },
  { code: "10", name: "Deck Equipment & Lifting", level: 1, groupCode: "10", parentCode: null, defaultZone: null, source: "master", sortOrder: 114 },
  { code: "10.1", name: "Anchoring Equipment", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 115 },
  { code: "10.2", name: "Mooring Equipment — Capstans", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 116 },
  { code: "10.3", name: "Cranes & Davits", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 117 },
  { code: "10.4", name: "Passerelle & Boarding Equipment", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 118 },
  { code: "10.5", name: "Safety Padeyes", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 119 },
  { code: "10.6", name: "Awnings & Covers", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 120 },
  { code: "10.7", name: "Hydraulic Power Units", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 121 },
  { code: "10.8", name: "Handrails & Guard Rails", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 122 },
  { code: "10.9", name: "Deck Lights", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 123 },
  { code: "10.10", name: "Teak Deck Coverings", level: 2, groupCode: "10", parentCode: "10", defaultZone: null, source: "master", sortOrder: 124 },
  { code: "11", name: "Tenders, Toys & Recreational Craft", level: 1, groupCode: "11", parentCode: null, defaultZone: null, source: "master", sortOrder: 125 },
  { code: "11.1", name: "Limo Tender", level: 2, groupCode: "11", parentCode: "11", defaultZone: null, source: "master", sortOrder: 126 },
  { code: "11.2", name: "Sport Tender", level: 2, groupCode: "11", parentCode: "11", defaultZone: null, source: "master", sortOrder: 127 },
  { code: "11.3", name: "Chase Boat", level: 2, groupCode: "11", parentCode: "11", defaultZone: null, source: "master", sortOrder: 128 },
  { code: "11.4", name: "Rescue / MOB Boat", level: 2, groupCode: "11", parentCode: "11", defaultZone: null, source: "master", sortOrder: 129 },
  { code: "11.5", name: "Jet Skis", level: 2, groupCode: "11", parentCode: "11", defaultZone: null, source: "master", sortOrder: 130 },
  { code: "11.6", name: "Water Sports & Dive Equipment", level: 2, groupCode: "11", parentCode: "11", defaultZone: null, source: "master", sortOrder: 131 },
  { code: "12", name: "Galley, Laundry & Hospitality", level: 1, groupCode: "12", parentCode: null, defaultZone: null, source: "master", sortOrder: 132 },
  { code: "12.1", name: "Galley Refrigeration", level: 2, groupCode: "12", parentCode: "12", defaultZone: null, source: "master", sortOrder: 133 },
  { code: "12.2", name: "Galley Cooking Equipment", level: 2, groupCode: "12", parentCode: "12", defaultZone: null, source: "master", sortOrder: 134 },
  { code: "12.3", name: "Galley Dishwashing", level: 2, groupCode: "12", parentCode: "12", defaultZone: null, source: "master", sortOrder: 135 },
  { code: "12.4", name: "Bar Equipment — Sundeck Bar", level: 2, groupCode: "12", parentCode: "12", defaultZone: null, source: "master", sortOrder: 136 },
  { code: "12.5", name: "Laundry Appliances", level: 2, groupCode: "12", parentCode: "12", defaultZone: null, source: "master", sortOrder: 137 },
  { code: "12.6", name: "Beauty Spa & Wellness Equipment", level: 2, groupCode: "12", parentCode: "12", defaultZone: null, source: "master", sortOrder: 138 },
  { code: "12.7", name: "Galley Grease Trap & Waste", level: 2, groupCode: "12", parentCode: "12", defaultZone: null, source: "master", sortOrder: 139 },
  { code: "13", name: "Accommodation & Interior", level: 1, groupCode: "13", parentCode: null, defaultZone: null, source: "master", sortOrder: 140 },
  { code: "13.1", name: "Furniture & Soft Furnishings", level: 2, groupCode: "13", parentCode: "13", defaultZone: null, source: "master", sortOrder: 141 },
  { code: "13.2", name: "Safes & Security Fittings", level: 2, groupCode: "13", parentCode: "13", defaultZone: null, source: "master", sortOrder: 142 },
  { code: "13.3", name: "Interior Doors & Access Control", level: 2, groupCode: "13", parentCode: "13", defaultZone: null, source: "master", sortOrder: 143 },
  { code: "14", name: "Medical & Health", level: 1, groupCode: "14", parentCode: null, defaultZone: null, source: "master", sortOrder: 144 },
  { code: "14.1", name: "MLC / SOLAS Statutory Medical Equipment", level: 2, groupCode: "14", parentCode: "14", defaultZone: null, source: "master", sortOrder: 145 },
  { code: "14.2", name: "Controlled Drugs & Prescription Medicines", level: 2, groupCode: "14", parentCode: "14", defaultZone: null, source: "master", sortOrder: 146 },
  { code: "14.3", name: "General Medical Supplies & OTC", level: 2, groupCode: "14", parentCode: "14", defaultZone: null, source: "master", sortOrder: 147 },
  { code: "14.4", name: "Sick Bay & Hospital Equipment", level: 2, groupCode: "14", parentCode: "14", defaultZone: null, source: "master", sortOrder: 148 },
  { code: "14.5", name: "Medevac & Emergency Medical Procedures", level: 2, groupCode: "14", parentCode: "14", defaultZone: null, source: "master", sortOrder: 149 },
  { code: "15", name: "Aviation & Helideck Operations", level: 1, groupCode: "15", parentCode: null, defaultZone: null, source: "master", sortOrder: 150 },
  { code: "15.1", name: "Helideck Structure & Surface", level: 2, groupCode: "15", parentCode: "15", defaultZone: null, source: "master", sortOrder: 151 },
  { code: "15.2", name: "Hangar Structure & Doors", level: 2, groupCode: "15", parentCode: "15", defaultZone: null, source: "master", sortOrder: 152 },
  { code: "15.3", name: "Helicopter Movement & Securing Systems", level: 2, groupCode: "15", parentCode: "15", defaultZone: null, source: "master", sortOrder: 153 },
  { code: "15.4", name: "Aviation Ground Handling Equipment", level: 2, groupCode: "15", parentCode: "15", defaultZone: null, source: "master", sortOrder: 154 },
  { code: "16", name: "Engineering — Inventory, Equip & Consumables", level: 1, groupCode: "16", parentCode: null, defaultZone: null, source: "master", sortOrder: 155 },
  { code: "16.1", name: "Measuring & Test Instruments", level: 2, groupCode: "16", parentCode: "16", defaultZone: null, source: "master", sortOrder: 156 },
  { code: "16.2", name: "Power Tools & Charging Equipment", level: 2, groupCode: "16", parentCode: "16", defaultZone: null, source: "master", sortOrder: 157 },
  { code: "16.3", name: "Hand Tools & Workshop Equipment", level: 2, groupCode: "16", parentCode: "16", defaultZone: null, source: "master", sortOrder: 158 },
  { code: "16.4", name: "Machinery Spares", level: 2, groupCode: "16", parentCode: "16", defaultZone: null, source: "master", sortOrder: 159 },
  { code: "16.5", name: "Lubricants & Hydraulic Fluids", level: 2, groupCode: "16", parentCode: "16", defaultZone: null, source: "master", sortOrder: 160 },
  { code: "16.6", name: "Filters, Gaskets & Seals", level: 2, groupCode: "16", parentCode: "16", defaultZone: null, source: "master", sortOrder: 161 },
  { code: "16.7", name: "Electrical & Instrumentation Consumables", level: 2, groupCode: "16", parentCode: "16", defaultZone: null, source: "master", sortOrder: 162 },
  { code: "16.8", name: "Paints, Coatings & Hull Consumables", level: 2, groupCode: "16", parentCode: "16", defaultZone: null, source: "master", sortOrder: 163 },
  { code: "17", name: "Deck — Inventory, Equip & Consumables", level: 1, groupCode: "17", parentCode: null, defaultZone: null, source: "master", sortOrder: 164 },
  { code: "17.1", name: "Deck Tools & Hardware", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 165 },
  { code: "17.2", name: "Mooring Lines & Ropes", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 166 },
  { code: "17.3", name: "Fenders & Fendering Equipment", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 167 },
  { code: "17.4", name: "Anchoring Consumables", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 168 },
  { code: "17.5", name: "Deck Safety Equipment & PPE", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 169 },
  { code: "17.6", name: "Tender & Toy Deck Gear", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 170 },
  { code: "17.7", name: "Painting & Surface Preparation Equipment", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 171 },
  { code: "17.8", name: "Navigation & Signal Consumables", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 172 },
  { code: "17.9", name: "Aviation PPE & Crew Equipment", level: 2, groupCode: "17", parentCode: "17", defaultZone: null, source: "master", sortOrder: 173 },
  { code: "18", name: "Interior — Inventory, Equip & Consumables", level: 1, groupCode: "18", parentCode: null, defaultZone: null, source: "master", sortOrder: 174 },
  { code: "18.1", name: "Laundry Appliances (installed)", level: 2, groupCode: "18", parentCode: "18", defaultZone: null, source: "master", sortOrder: 175 },
  { code: "18.2", name: "Cleaning Equipment & Machinery", level: 2, groupCode: "18", parentCode: "18", defaultZone: null, source: "master", sortOrder: 176 },
  { code: "18.3", name: "Cleaning Products & Chemicals", level: 2, groupCode: "18", parentCode: "18", defaultZone: null, source: "master", sortOrder: 177 },
  { code: "18.4", name: "Guest Cabin Consumables & Amenities", level: 2, groupCode: "18", parentCode: "18", defaultZone: null, source: "master", sortOrder: 178 },
  { code: "18.5", name: "Linen & Soft Furnishings Inventory", level: 2, groupCode: "18", parentCode: "18", defaultZone: null, source: "master", sortOrder: 179 },
  { code: "18.6", name: "Uniforms & Crew Clothing", level: 2, groupCode: "18", parentCode: "18", defaultZone: null, source: "master", sortOrder: 180 },
  { code: "18.7", name: "Flowers, Decor & Presentation", level: 2, groupCode: "18", parentCode: "18", defaultZone: null, source: "master", sortOrder: 181 },
  { code: "18.8", name: "Stationery & Office Supplies", level: 2, groupCode: "18", parentCode: "18", defaultZone: null, source: "master", sortOrder: 182 },
  { code: "19", name: "Galley — Inventory, Equip & Consumables", level: 1, groupCode: "19", parentCode: null, defaultZone: null, source: "master", sortOrder: 183 },
  { code: "19.1", name: "Galley Small Equipment & Utensils", level: 2, groupCode: "19", parentCode: "19", defaultZone: null, source: "master", sortOrder: 184 },
  { code: "19.2", name: "Crockery, Glassware & Cutlery", level: 2, groupCode: "19", parentCode: "19", defaultZone: null, source: "master", sortOrder: 185 },
  { code: "19.3", name: "Cookware & Bakeware", level: 2, groupCode: "19", parentCode: "19", defaultZone: null, source: "master", sortOrder: 186 },
  { code: "19.4", name: "Dry Goods & Provisions", level: 2, groupCode: "19", parentCode: "19", defaultZone: null, source: "master", sortOrder: 187 },
  { code: "19.5", name: "Beverages & Bar Stock", level: 2, groupCode: "19", parentCode: "19", defaultZone: null, source: "master", sortOrder: 188 },
  { code: "19.6", name: "Galley Cleaning Products & Food Safety", level: 2, groupCode: "19", parentCode: "19", defaultZone: null, source: "master", sortOrder: 189 },
  { code: "19.7", name: "Packaging & Disposables", level: 2, groupCode: "19", parentCode: "19", defaultZone: null, source: "master", sortOrder: 190 },
  { code: "20", name: "Laundry — Inventory, Equip & Consumables", level: 1, groupCode: "20", parentCode: null, defaultZone: null, source: "master", sortOrder: 191 },
  { code: "20.1", name: "Laundry Appliances", level: 2, groupCode: "20", parentCode: "20", defaultZone: null, source: "master", sortOrder: 192 },
  { code: "20.2", name: "Ironing & Pressing Equipment", level: 2, groupCode: "20", parentCode: "20", defaultZone: null, source: "master", sortOrder: 193 },
  { code: "20.3", name: "Laundry Chemicals & Detergents", level: 2, groupCode: "20", parentCode: "20", defaultZone: null, source: "master", sortOrder: 194 },
  { code: "20.4", name: "Linen Processing Consumables", level: 2, groupCode: "20", parentCode: "20", defaultZone: null, source: "master", sortOrder: 195 },
  { code: "20.5", name: "Sewing & Repair Kit", level: 2, groupCode: "20", parentCode: "20", defaultZone: null, source: "master", sortOrder: 196 },
];
